version: '2.2'

services:
  homeassist:
    image: "homeassistant/home-assistant:stable"
    restart: always
    network_mode: host
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "homeassist_conf:/config"
  mosquitto:
    image: "eclipse-mosquitto:latest"
    restart: always
    volumes:
      - "mosquitto_data:/mosquitto/data"
      - "mosquitto_log:/mosquitto/log"
      - "mosquitto_conf:/mosquitto/config"
    ports:
      - 1883:1883 
      - 9001:9001

volumes:
  homeassist_conf:
    driver: local
  mosquitto_data:
    driver: local
  mosquitto_log:
    driver: local
  mosquitto_conf:
    driver: local

